version: '3.8'

services:
  mongo:
    container_name: mongodb-product
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/mongodb/db:/data/db
    networks:
      - product-net

  mongo-express:
    container_name: mongo-express-product
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:latest
    restart: always
    ports:
      - "80:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - product-net

volumes:
  mongo-data:

networks:
  product-net:
    driver: bridge