server:
  port: 8081
spring:
  application:
    name: category-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: admin
      database: db-category
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
topic:
  product:
    consumer:
      name: product-consumer.request.topic.v1
      group-id: majo
    producer:
      name: product-producer.request.topic.v1