server:
  port: 8080
spring:
  application:
    name: product-service
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: admin
      database: db-products
      port: 27017
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
topic:
  product:
    consumer:
      name: product.response.topic.v1
      group-id: majo
    producer:
      name: product.request.topic.v1