server:
  port: ${PORT:8888}
spring:
  config:
    import: optional:file:dev.env[.properties]
  application:
      name: config-service
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          default-label: main
          search-paths:
            - ${PATH}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
